# Generated by Django 4.2 on 2024-09-28 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("patient", "0001_initial"),
        ("catalog", "0002_medicine_illnesses"),
    ]

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Register created timestamp"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last update timestampt"
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("total_price", models.FloatField()),
                (
                    "donated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "donation",
            },
        ),
        migrations.CreateModel(
            name="DonationMedicine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("expire_date", models.DateField()),
                ("batch", models.CharField(blank=True, max_length=15, null=True)),
                ("unit_price", models.FloatField()),
                ("total_price", models.FloatField()),
                (
                    "donation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="donor.donation"
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.medicine",
                    ),
                ),
            ],
            options={
                "db_table": "donation_medicine",
            },
        ),
        migrations.CreateModel(
            name="Expired",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("expired_at", models.DateField()),
                (
                    "donation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="donor.donation"
                    ),
                ),
                (
                    "medicine_donated",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="donor.donationmedicine",
                    ),
                ),
            ],
            options={
                "db_table": "expired",
            },
        ),
        migrations.CreateModel(
            name="DeliveredDonation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("other_notes", models.TextField(blank=True, null=True)),
                (
                    "donation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="donor.donation"
                    ),
                ),
                (
                    "medicine_donated",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="donor.donationmedicine",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patient",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
