# Generated by Django 4.2 on 2024-09-28 02:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_medicine_illnesses"),
        ("donor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("checked_at", models.DateField()),
                ("needed", models.IntegerField()),
                ("available", models.IntegerField()),
                ("other_notes", models.TextField()),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.medicine",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
