# Generated by Django 4.2 on 2024-09-27 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Register created timestamp"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last update timestampt"
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("first_names", models.CharField(max_length=255)),
                ("last_names", models.CharField(max_length=255)),
                ("document", models.CharField(max_length=10)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("address", models.CharField(max_length=255)),
                (
                    "phone_number1",
                    models.CharField(blank=True, null=True, verbose_name=11),
                ),
                (
                    "phone_number2",
                    models.CharField(blank=True, null=True, verbose_name=11),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "male"), ("F", "female")], max_length=1
                    ),
                ),
                (
                    "purchase_power",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalog.sector"
                    ),
                ),
            ],
            options={
                "db_table": "patient",
            },
        ),
    ]
