# Generated by Django 4.2 on 2024-09-28 02:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_medicinecontainer"),
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientTreatment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Register created timestamp"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last update timestampt"
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("quantity", models.IntegerField()),
                ("available", models.BooleanField(default=False)),
                ("done", models.DateTimeField(blank=True, null=True)),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.medicinecontainer",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patient",
                    ),
                ),
            ],
            options={
                "db_table": "patient_treatment",
            },
        ),
        migrations.CreateModel(
            name="PatientHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("bed_bound", models.BooleanField(default=False)),
                ("diabetes", models.BooleanField(default=False)),
                ("erc", models.BooleanField(default=False)),
                ("iam", models.BooleanField(default=False)),
                ("acv", models.BooleanField(default=False)),
                ("dyslipidemia", models.BooleanField(default=False)),
                ("obesity", models.BooleanField(default=False)),
                ("smoking", models.BooleanField(default=False)),
                ("allergies", models.BooleanField(default=False)),
                ("other_meds", models.TextField()),
                ("other_notes", models.TextField()),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patient",
                    ),
                ),
            ],
            options={
                "db_table": "patient_history",
            },
        ),
    ]
