# Generated by Django 4.2 on 2024-09-28 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="illnesses",
            field=models.ManyToManyField(
                through="catalog.IllnessMedicine", to="catalog.illness"
            ),
        ),
    ]
